package Telas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Conexoes.*;


public class TelaLogin extends javax.swing.JFrame {

    Conexao conecta = new Conexao();
    
    
    public TelaLogin() {
        initComponents();
        
        //fazer a conexao com o banco de dados
        conecta.conectar();
        
        
        //Setar Imagens Nos Componentes
        
        ImageIcon Logo = new ImageIcon("src/imagens/Logo_Loja.JPG");
        Logo.setImage(Logo.getImage().getScaledInstance(
                lblLogo.getWidth(), 
                lblLogo.getHeight(),
                1));
        lblLogo.setIcon(Logo);
        
        
        ImageIcon Minimizar = new ImageIcon("src/imagens/IconeMinimizar.png");
        Minimizar.setImage(Minimizar.getImage().getScaledInstance(
                btnMinimizar.getWidth(), 
                btnMinimizar.getHeight(), 
                1));
        btnMinimizar.setIcon(Minimizar);
        
        
        ImageIcon Fechar = new ImageIcon("src/imagens/IconeFechar.png");
        Fechar.setImage(Fechar.getImage().getScaledInstance(
                btnFechar.getWidth(),
                btnFechar.getHeight(),
                1));
        btnFechar.setIcon(Fechar); 
        
        //Fim do Setar Imagens nos Componentes
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        jSeparatorNome = new javax.swing.JSeparator();
        jSeparatorCpf = new javax.swing.JSeparator();
        lblCPF = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAcessar = new javax.swing.JButton();
        btnDuvida = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        txtSenha = new javax.swing.JTextField();
        bg = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLogin.setBackground(new java.awt.Color(102, 102, 102));
        pnlLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pnlLogin.setLayout(null);

        lblNome.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Senha:");
        pnlLogin.add(lblNome);
        lblNome.setBounds(30, 120, 70, 20);

        jSeparatorNome.setForeground(new java.awt.Color(255, 255, 255));
        pnlLogin.add(jSeparatorNome);
        jSeparatorNome.setBounds(100, 140, 110, 10);

        jSeparatorCpf.setForeground(new java.awt.Color(255, 255, 255));
        pnlLogin.add(jSeparatorCpf);
        jSeparatorCpf.setBounds(100, 100, 110, 10);

        lblCPF.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("Login:");
        pnlLogin.add(lblCPF);
        lblCPF.setBounds(40, 80, 60, 20);

        txtLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLogin.setBorder(null);
        txtLogin.setOpaque(false);
        pnlLogin.add(txtLogin);
        txtLogin.setBounds(100, 70, 110, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        btnAcessar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAcessar.setForeground(new java.awt.Color(255, 255, 255));
        btnAcessar.setText("Acessar");
        btnAcessar.setBorder(null);
        btnAcessar.setContentAreaFilled(false);
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcessar);
        btnAcessar.setBounds(0, 0, 110, 30);

        pnlLogin.add(jPanel1);
        jPanel1.setBounds(70, 170, 110, 30);

        btnDuvida.setBackground(new java.awt.Color(255, 255, 255));
        btnDuvida.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnDuvida.setText("?");
        btnDuvida.setToolTipText("Minimizar");
        btnDuvida.setBorder(null);
        btnDuvida.setContentAreaFilled(false);
        btnDuvida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuvidaActionPerformed(evt);
            }
        });
        pnlLogin.add(btnDuvida);
        btnDuvida.setBounds(120, 10, 20, 20);

        btnFechar.setBackground(new java.awt.Color(0, 0, 0));
        btnFechar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnFechar.setToolTipText("Fechar");
        btnFechar.setBorder(null);
        btnFechar.setContentAreaFilled(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlLogin.add(btnFechar);
        btnFechar.setBounds(200, 10, 20, 20);

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnMinimizar.setToolTipText("Minimizar");
        btnMinimizar.setBorder(null);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        pnlLogin.add(btnMinimizar);
        btnMinimizar.setBounds(160, 10, 20, 20);

        txtSenha.setBackground(new java.awt.Color(102, 102, 102));
        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSenha.setBorder(null);
        pnlLogin.add(txtSenha);
        txtSenha.setBounds(100, 110, 110, 30);

        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(310, 0, 240, 280);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(null);
        bg.add(lblLogo);
        lblLogo.setBounds(0, 0, 310, 280);

        getContentPane().add(bg);
        bg.setBounds(0, 0, 310, 280);

        setSize(new java.awt.Dimension(548, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnDuvidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuvidaActionPerformed
        JOptionPane.showMessageDialog(null, "Apenas Funcionarios Cadastrados!");

    }//GEN-LAST:event_btnDuvidaActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        TelaPrincipal principal = new TelaPrincipal();
        
        if("admin".equals(txtLogin.getText())){
            if("admin".equals(txtSenha.getText())){
                principal.setVisible(true);
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(null,"Senha Incorreta");
                txtSenha.setText("");
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Usuario ou Senha Incorretos");
            txtLogin.setText("");
            txtSenha.setText("");
        }
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnDuvida;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparatorCpf;
    private javax.swing.JSeparator jSeparatorNome;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
