/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import BeansObjetos.BeansProduto;
import DaoObjetos.DaoProdutos;
import static java.awt.SystemColor.control;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Otavio
 */
public class TelaTabelaProduto extends javax.swing.JFrame {
    
    BeansProduto BeansProd = new BeansProduto();  
    DaoProdutos DaoProd = new DaoProdutos();
    
    public TelaTabelaProduto() {
        initComponents();
        pnlEditar.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProduto = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jSeparatorCpf = new javax.swing.JSeparator();
        btnPesquisaTabela = new javax.swing.JButton();
        pnlCadastro = new javax.swing.JPanel();
        txtPesquisaEditar = new javax.swing.JTextField();
        jSeparatorCpf2 = new javax.swing.JSeparator();
        btnPesquisaEditar = new javax.swing.JButton();
        pnlEditar = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jSeparatorNome = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lbl1Tel = new javax.swing.JLabel();
        txt1Tel = new javax.swing.JFormattedTextField();
        jSeparator1Tel = new javax.swing.JSeparator();
        txt2Tel = new javax.swing.JFormattedTextField();
        jSeparator2Tel = new javax.swing.JSeparator();
        lbl2Tel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparatorEmail = new javax.swing.JSeparator();
        lblFornecedor = new javax.swing.JLabel();
        jSeparatorEmail1 = new javax.swing.JSeparator();
        txtFornecedor = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jSeparatorEmail2 = new javax.swing.JSeparator();
        lbMarca = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        TabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tel1", "Tel2", "Email", "Fornecedor", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaProduto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 550, 370);

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPesquisa.setBorder(null);
        txtPesquisa.setOpaque(false);
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(100, 50, 270, 30);

        jSeparatorCpf.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparatorCpf);
        jSeparatorCpf.setBounds(100, 80, 270, 10);

        btnPesquisaTabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisaTabela.setText("Pesquisar");
        btnPesquisaTabela.setBorder(null);
        btnPesquisaTabela.setContentAreaFilled(false);
        btnPesquisaTabela.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPesquisaTabelaMouseMoved(evt);
            }
        });
        btnPesquisaTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaTabelaMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaTabela);
        btnPesquisaTabela.setBounds(380, 50, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 0, 570, 510);

        pnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setForeground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setLayout(null);

        txtPesquisaEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPesquisaEditar.setBorder(null);
        txtPesquisaEditar.setOpaque(false);
        pnlCadastro.add(txtPesquisaEditar);
        txtPesquisaEditar.setBounds(50, 50, 270, 30);

        jSeparatorCpf2.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadastro.add(jSeparatorCpf2);
        jSeparatorCpf2.setBounds(50, 80, 270, 10);

        btnPesquisaEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisaEditar.setText("Pesquisar");
        btnPesquisaEditar.setBorder(null);
        btnPesquisaEditar.setContentAreaFilled(false);
        btnPesquisaEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPesquisaEditarMouseMoved(evt);
            }
        });
        btnPesquisaEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaEditarMouseExited(evt);
            }
        });
        btnPesquisaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEditarActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnPesquisaEditar);
        btnPesquisaEditar.setBounds(330, 50, 110, 30);

        pnlEditar.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditar.setLayout(null);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.setBorder(null);
        txtNome.setEnabled(false);
        txtNome.setOpaque(false);
        pnlEditar.add(txtNome);
        txtNome.setBounds(130, 30, 270, 30);

        jSeparatorNome.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparatorNome);
        jSeparatorNome.setBounds(130, 60, 270, 10);

        lblNome.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNome.setText("Nome:");
        pnlEditar.add(lblNome);
        lblNome.setBounds(60, 40, 70, 20);

        lbl1Tel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbl1Tel.setText("¹Tel:");
        pnlEditar.add(lbl1Tel);
        lbl1Tel.setBounds(80, 80, 50, 20);

        txt1Tel.setBorder(null);
        try {
            txt1Tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt1Tel.setEnabled(false);
        txt1Tel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pnlEditar.add(txt1Tel);
        txt1Tel.setBounds(130, 70, 270, 30);

        jSeparator1Tel.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparator1Tel);
        jSeparator1Tel.setBounds(130, 100, 270, 10);

        txt2Tel.setBorder(null);
        try {
            txt2Tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt2Tel.setEnabled(false);
        txt2Tel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pnlEditar.add(txt2Tel);
        txt2Tel.setBounds(130, 110, 270, 30);

        jSeparator2Tel.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparator2Tel);
        jSeparator2Tel.setBounds(130, 140, 270, 10);

        lbl2Tel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbl2Tel.setText("²Tel:");
        pnlEditar.add(lbl2Tel);
        lbl2Tel.setBounds(80, 120, 50, 20);

        lblEmail.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEmail.setText("Email:");
        pnlEditar.add(lblEmail);
        lblEmail.setBounds(60, 160, 70, 20);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setEnabled(false);
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlEditar.add(txtEmail);
        txtEmail.setBounds(130, 150, 270, 30);

        jSeparatorEmail.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparatorEmail);
        jSeparatorEmail.setBounds(130, 180, 270, 10);

        lblFornecedor.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblFornecedor.setText("Fornecedor:");
        pnlEditar.add(lblFornecedor);
        lblFornecedor.setBounds(10, 200, 130, 20);

        jSeparatorEmail1.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparatorEmail1);
        jSeparatorEmail1.setBounds(130, 220, 270, 10);

        txtFornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFornecedor.setBorder(null);
        txtFornecedor.setEnabled(false);
        txtFornecedor.setOpaque(false);
        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });
        pnlEditar.add(txtFornecedor);
        txtFornecedor.setBounds(130, 190, 270, 30);

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMarca.setBorder(null);
        txtMarca.setEnabled(false);
        txtMarca.setOpaque(false);
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        pnlEditar.add(txtMarca);
        txtMarca.setBounds(130, 230, 270, 30);

        jSeparatorEmail2.setForeground(new java.awt.Color(0, 0, 0));
        pnlEditar.add(jSeparatorEmail2);
        jSeparatorEmail2.setBounds(130, 260, 270, 10);

        lbMarca.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbMarca.setText("Marca:");
        pnlEditar.add(lbMarca);
        lbMarca.setBounds(60, 240, 70, 20);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCancelarMouseMoved(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        pnlEditar.add(btnCancelar);
        btnCancelar.setBounds(70, 330, 90, 40);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEditar.setContentAreaFilled(false);
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlEditar.add(btnEditar);
        btnEditar.setBounds(170, 330, 90, 40);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSalvarMouseMoved(evt);
            }
        });
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlEditar.add(btnSalvar);
        btnSalvar.setBounds(270, 330, 90, 40);

        pnlCadastro.add(pnlEditar);
        pnlEditar.setBounds(0, 90, 440, 420);

        getContentPane().add(pnlCadastro);
        pnlCadastro.setBounds(0, 0, 440, 510);

        setSize(new java.awt.Dimension(1002, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseMoved
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_btnCancelarMouseMoved

    private void btnPesquisaEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaEditarMouseMoved
        btnPesquisaEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_btnPesquisaEditarMouseMoved

    private void btnPesquisaEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaEditarMouseExited
        btnPesquisaEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnPesquisaEditarMouseExited

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
       btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnSalvarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseMoved
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_btnSalvarMouseMoved

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnPesquisaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEditarActionPerformed

            pnlEditar.setVisible(true);
            
            BeansProd.setPesquisa(txtPesquisaEditar.getText());
            BeansProduto prod1 = DaoProd.buscaProduto(BeansProd);
            txtNome.setText(prod1.getNome());
            txt1Tel.setText(prod1.getTel1());
            txt2Tel.setText(prod1.getTel2());
            txtEmail.setText(prod1.getEmail());
            txtFornecedor.setText(prod1.getFornecedor());
            txtMarca.setText(prod1.getMarca());

    }//GEN-LAST:event_btnPesquisaEditarActionPerformed

    private void btnPesquisaTabelaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaTabelaMouseMoved
       btnPesquisaTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_btnPesquisaTabelaMouseMoved

    private void btnPesquisaTabelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaTabelaMouseExited
        btnPesquisaTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnPesquisaTabelaMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtNome.setEnabled(true);
        txt1Tel.setEnabled(true);
        txt2Tel.setEnabled(true);
        txtEmail.setEnabled(true);
        txtFornecedor.setEnabled(true);
        txtMarca.setEnabled(true);
        txtPesquisaEditar.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        //Desabelita os Campos
        txtNome.setEnabled(false);
        txt1Tel.setEnabled(false);
        txt2Tel.setEnabled(false);
        txtEmail.setEnabled(false);
        txtFornecedor.setEnabled(false);
        txtMarca.setEnabled(false);
        txtPesquisaEditar.setEnabled(true);
        
        //Limpa os Campos
        txtNome.setText("");
        txt1Tel.setText("");
        txt2Tel.setText("");
        txtEmail.setText("");
        txtFornecedor.setText("");
        txtMarca.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPesquisaEditar;
    private javax.swing.JButton btnPesquisaTabela;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1Tel;
    private javax.swing.JSeparator jSeparator2Tel;
    private javax.swing.JSeparator jSeparatorCpf;
    private javax.swing.JSeparator jSeparatorCpf2;
    private javax.swing.JSeparator jSeparatorEmail;
    private javax.swing.JSeparator jSeparatorEmail1;
    private javax.swing.JSeparator jSeparatorEmail2;
    private javax.swing.JSeparator jSeparatorNome;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbl1Tel;
    private javax.swing.JLabel lbl2Tel;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JFormattedTextField txt1Tel;
    private javax.swing.JFormattedTextField txt2Tel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPesquisaEditar;
    // End of variables declaration//GEN-END:variables
}
